# Generated by Django 5.2.15 on 2026-06-29 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Quốc gia')),
            ],
            options={
                'verbose_name': 'Quốc gia',
                'verbose_name_plural': 'Quốc gia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên phim')),
                ('title_original', models.CharField(blank=True, max_length=200, verbose_name='Tên gốc')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('poster', models.URLField(blank=True, max_length=500, verbose_name='URL poster')),
                ('thumb', models.URLField(blank=True, max_length=500, verbose_name='URL thumbnail')),
                ('release_year', models.IntegerField(verbose_name='Năm phát hành')),
                ('movie_type', models.CharField(choices=[('single', 'Phim lẻ'), ('series', 'Phim bộ'), ('cinema', 'Phim chiếu rạp'), ('animation', 'Hoạt hình & Anime')], default='single', max_length=20, verbose_name='Loại phim')),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('vietsub', 'Vietsub'), ('thuyet_minh', 'Thuyết Minh'), ('long_tieng', 'Lồng Tiếng')], default='HD', max_length=20, verbose_name='Chất lượng')),
                ('episode_count', models.IntegerField(blank=True, null=True, verbose_name='Số tập')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Phim đề cử')),
                ('views', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('ophim_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='OPHim ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.country', verbose_name='Quốc gia')),
                ('genres', models.ManyToManyField(to='movie_app.genre', verbose_name='Thể loại')),
            ],
            options={
                'verbose_name': 'Phim',
                'verbose_name_plural': 'Phim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='Vietsub', max_length=100, verbose_name='Tên server')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tập')),
                ('slug', models.CharField(blank=True, max_length=100, verbose_name='Slug tập')),
                ('link_embed', models.URLField(blank=True, max_length=1000, verbose_name='Link embed')),
                ('link_m3u8', models.URLField(blank=True, max_length=1000, verbose_name='Link m3u8')),
                ('episode_number', models.IntegerField(default=0, verbose_name='Số tập')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie_app.movie', verbose_name='Phim')),
            ],
            options={
                'verbose_name': 'Tập phim',
                'verbose_name_plural': 'Tập phim',
                'ordering': ['sort_order', 'episode_number'],
            },
        ),
    ]
