# Generated by Django 6.0.6 on 2026-06-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên phim')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('poster', models.URLField(blank=True, max_length=500, verbose_name='URL poster')),
                ('release_year', models.IntegerField(verbose_name='Năm phát hành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phim',
                'verbose_name_plural': 'Phim',
                'ordering': ['-created_at'],
            },
        ),
    ]
