# Generated by Django 6.0.6 on 2026-06-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên thể loại')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie_app.genre', verbose_name='Thể loại'),
        ),
    ]
