# Generated by Django 6.0.6 on 2026-06-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_genre_movie_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Quốc gia')),
            ],
            options={
                'verbose_name': 'Quốc gia',
                'verbose_name_plural': 'Quốc gia',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='episode_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số tập'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Phim đề cử'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('single', 'Phim lẻ'), ('series', 'Phim bộ'), ('cinema', 'Phim chiếu rạp'), ('animation', 'Hoạt hình & Anime')], default='single', max_length=20, verbose_name='Loại phim'),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(choices=[('HD', 'HD'), ('vietsub', 'Vietsub'), ('thuyet_minh', 'Thuyết Minh'), ('long_tieng', 'Lồng Tiếng')], default='HD', max_length=20, verbose_name='Chất lượng'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_original',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên gốc'),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Lượt xem'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.country', verbose_name='Quốc gia'),
        ),
    ]
