name: Deploy

on:
  push:
    branches:
      - uat
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .env
        run: cp /home/snine/actions-runner/.env.bak .env

      - name: Deploy to UAT
        if: github.ref_name == 'uat'
        run: |
          APP_PORT=8001 DJANGO_DB_PATH=/app/data/uat.sqlite3 docker compose -p uat up -d --build
          docker compose -p uat exec -T web python manage.py migrate --noinput

      - name: Deploy to Production
        if: github.ref_name == 'main'
        run: |
          DJANGO_DB_PATH=/app/data/main.sqlite3 docker compose up -d --build
          docker compose exec -T web python manage.py migrate --noinput
